% -------------------------------------------------------------------
%  Generated by MATLAB on 22-Oct-2018 01:24:29
%  MATLAB version: 8.5.0.197613 (R2015a)
% -------------------------------------------------------------------
saveVarsMat = load('AudioProccessing.mat');

A = 0.3;

N = 48000;

a1 = saveVarsMat.a1; % <618496x2 double> too many elements

a2 = saveVarsMat.a2; % <1x705632 double> too many elements

f = 440;

f_axis = saveVarsMat.f_axis; % <1x48000 double> too many elements

fs = 48000;

g = saveVarsMat.g; % <618496x2 double> too many elements

hop = 64;

m = saveVarsMat.m; % <1x705632 double> too many elements

magTransform = saveVarsMat.magTransform; % <1x48000 double> too many elements

nfft = 128;

s = saveVarsMat.s; % <1x705632 double> too many elements

t = saveVarsMat.t; % <1x22051 double> too many elements

t1 = saveVarsMat.t1; % <1x22051 double> too many elements

t10 = saveVarsMat.t10; % <1x22051 double> too many elements

t11 = saveVarsMat.t11; % <1x22051 double> too many elements

t12 = saveVarsMat.t12; % <1x22051 double> too many elements

t2 = saveVarsMat.t2; % <1x22051 double> too many elements

t3 = saveVarsMat.t3; % <1x22051 double> too many elements

t4 = saveVarsMat.t4; % <1x22051 double> too many elements

t5 = saveVarsMat.t5; % <1x22051 double> too many elements

t6 = saveVarsMat.t6; % <1x22051 double> too many elements

t7 = saveVarsMat.t7; % <1x22051 double> too many elements

t8 = saveVarsMat.t8; % <1x22051 double> too many elements

t9 = saveVarsMat.t9; % <1x22051 double> too many elements

transform = saveVarsMat.transform; % <1x48000 double> too many elements

win = 128;

clear saveVarsMat;
